"""
exact.py -- Exact continuous-time Markov chain (CTMC) tools for the rotation game.

Everything the event-driven simulator (rotation_game.py) estimates by Monte Carlo
can be computed exactly for the same Markov model.

  * time-average availability    = stationary P[up]
  * (alpha,T)-interval availability = P[up throughout [0,T]] for a chain started
    in stationarity
        = pi_U  expm(Q_UU T)  1,
    where U is the set of up states, pi_U the stationary probabilities of those
    states, and Q_UU the generator restricted to U (transitions into the down
    set are killed).  This is exactly the quantity the simulator's
    interval_up_probability() estimates (the fraction of window start times t0
    such that [t0, t0+T] contains no down time).

The address layer and the name layer of the model are driven by independent
clocks, so the system is up throughout a window iff both layers are, and

    interval availability = window_addr(T) * window_name(T),
    time-average availability = P[addr up] * P[name up].

Two numerical engines are provided.

  1. Birth-death chains (address layer, constant-rate and per-unit name pools,
     range-blocked address layer). These chains are reversible, so the killed
     generator is similar to a symmetric tridiagonal matrix:
        S = D^{1/2} Q_UU D^{-1/2},   D = diag(pi_U),
     and   pi_U expm(Q_UU T) 1 = s' expm(S T) s,  s = sqrt(pi_U)
                               = sum_m (v_m' s)^2 exp(lambda_m T).
     All weights are non-negative and the eigenvalues are negative, so the
     result is accurate to ~1e-14 absolute and cheap for many T at once.
     The stationary law is computed by detailed balance in log space.

  2. General chains (batch burns, strategic timing censor, providers, mint-time
     exposure, synchronized address discovery). The state space is generated by
     breadth-first search from an initial state, the off-diagonal generator is
     stored as a sum of sparse matrices that are linear in the named rate
     parameters (so a sweep over beta only rescales them), the stationary law is
     a direct (dense or sparse LU) solve, and the window probability uses
     scipy's expm (small chains) or expm_multiply (large chains).

Time unit: 1/lam_intro (lam_intro = 1) throughout, as in the paper.

Run `python3 exact.py` for a self-test (spectral vs dense expm, closed forms).
"""

from collections import deque

import numpy as np
import scipy.sparse as sp
from scipy.integrate import quad
from scipy.linalg import eigh_tridiagonal, expm
from scipy.optimize import brentq
from scipy.sparse.linalg import expm_multiply, spsolve
from scipy.special import logsumexp

# chains larger than this use sparse/Krylov routines instead of dense ones
_DENSE_MAX = 400
_SPECTRAL_MAX = 200     # above this the Krylov path is faster (same accuracy)


# =========================================================================== #
#  1. Birth-death chains on {0,...,m}, down set = {0}
# =========================================================================== #
def _as_rates(births, deaths):
    b = np.asarray(births, dtype=float).ravel()
    d = np.asarray(deaths, dtype=float).ravel()
    if b.shape != d.shape:
        raise ValueError("births and deaths must have the same length m")
    if np.any(b < 0) or np.any(d < 0):
        raise ValueError("rates must be non-negative")
    return b, d


def bd_log_stationary(births, deaths):
    """log of the stationary law of a birth-death chain on {0..m}.

    births[i] is the rate i -> i+1 and deaths[i] the rate i+1 -> i
    (i = 0..m-1). All rates must be positive (irreducible chain).
    Detailed balance: pi_{i+1} = pi_i * births[i] / deaths[i].
    """
    b, d = _as_rates(births, deaths)
    if np.any(b <= 0) or np.any(d <= 0):
        raise ValueError("bd_log_stationary needs strictly positive rates")
    logpi = np.zeros(len(b) + 1)
    logpi[1:] = np.cumsum(np.log(b) - np.log(d))
    return logpi - logsumexp(logpi)


def bd_stationary(births, deaths):
    """Stationary law of a birth-death chain on {0..m} (see bd_log_stationary).
    Degenerate cases: all deaths zero -> point mass at m; all births zero ->
    point mass at 0."""
    b, d = _as_rates(births, deaths)
    m = len(b)
    if np.all(d == 0) and np.all(b > 0):
        pi = np.zeros(m + 1)
        pi[m] = 1.0
        return pi
    if np.all(b == 0) and np.all(d > 0):
        pi = np.zeros(m + 1)
        pi[0] = 1.0
        return pi
    return np.exp(bd_log_stationary(b, d))


def _bd_killed_tridiag(b, d):
    """Diagonal and symmetrized off-diagonal of the killed generator on 1..m."""
    m = len(b)
    birth_from = np.append(b[1:], 0.0)       # birth from state i = 1..m
    death_from = d                            # death from state i = 1..m (d[i-1])
    diag = -(birth_from + death_from)
    off = np.sqrt(b[1:] * d[1:])              # S[i,i+1] = sqrt(b_i d_i), i = 1..m-1
    return diag, off


def bd_window(births, deaths, T):
    """P[state >= 1 throughout [0,T]] for a stationary birth-death chain.

    births[i]: rate i -> i+1, deaths[i]: rate i+1 -> i (i = 0..m-1); the down
    set is {0}. T may be a scalar or an array. Uses the symmetric spectral
    form (exact up to rounding) for m <= 200 and a Krylov expm-vector product
    on the symmetrized matrix for larger m.
    """
    b, d = _as_rates(births, deaths)
    Ts = np.atleast_1d(np.asarray(T, dtype=float))
    scalar = np.ndim(T) == 0
    m = len(b)
    # degenerate chains
    if np.all(d == 0) and np.all(b > 0):          # never moves down -> always up
        out = np.ones_like(Ts)
        return float(out[0]) if scalar else out
    if np.all(b == 0) and np.all(d > 0):          # absorbed at 0 -> always down
        out = np.zeros_like(Ts)
        return float(out[0]) if scalar else out
    logpi = bd_log_stationary(b, d)
    s = np.exp(0.5 * logpi[1:])                   # sqrt(pi_U)
    diag, off = _bd_killed_tridiag(b, d)
    if m == 1:
        out = s[0] ** 2 * np.exp(min(diag[0], 0.0) * Ts)
    elif m <= _SPECTRAL_MAX:
        lam, V = eigh_tridiagonal(diag, off)
        lam = np.minimum(lam, 0.0)                # killed chain: lam < 0 exactly
        w = (V.T @ s) ** 2
        out = np.exp(np.outer(Ts, lam)) @ w
    else:
        S = sp.diags([off, diag, off], [-1, 0, 1], format="csr")
        out = np.array([float(s @ expm_multiply(S * t, s)) for t in Ts])
    out = np.clip(out, 0.0, 1.0)
    return float(out[0]) if scalar else out


def bd_window_dense(births, deaths, T):
    """Reference implementation with a dense matrix exponential (for tests)."""
    b, d = _as_rates(births, deaths)
    pi = np.exp(bd_log_stationary(b, d))
    m = len(b)
    Q = np.zeros((m + 1, m + 1))
    for i in range(m):
        Q[i, i + 1] = b[i]
        Q[i + 1, i] = d[i]
    np.fill_diagonal(Q, -Q.sum(axis=1))
    QUU = Q[1:, 1:]
    return float(pi[1:] @ expm(QUU * T) @ np.ones(m))


# ---- the two layers of the paper's model ---------------------------------- #
def addr_rates(n, lam_a, mu):
    """Address layer: c = number of clear endpoints in {0..n}.
    c -> c+1 at mu*(n-c) (rotation away from a blocked address),
    c -> c-1 at lam_a*c (discovery and block of a clear address)."""
    c = np.arange(n)
    return mu * (n - c), lam_a * (c + 1.0)


def addr_window(n, lam_a, mu, T):
    """Address-layer window probability P[>=1 clear address throughout [0,T]]."""
    b, d = addr_rates(n, lam_a, mu)
    return bd_window(b, d, T)


def addr_timeavg(n, lam_a, mu):
    """Address factor c_a = 1 - (lam_a/(lam_a+mu))^n (Lemma 1)."""
    if lam_a <= 0:
        return 1.0
    return 1.0 - (lam_a / (lam_a + mu)) ** n


def name_rates_constant(kmax, lam_intro, lam_disc):
    """Constant-rate pool (Proposition: name pool): K -> K+1 at lam_intro
    (K<kmax), K -> K-1 at lam_disc (K>=1)."""
    return np.full(kmax, float(lam_intro)), np.full(kmax, float(lam_disc))


def name_rates_perunit(kmax, lam_intro, delta):
    """Per-unit discovery pool (the paper's per-name burn rates): K -> K-1 at
    delta*K."""
    return np.full(kmax, float(lam_intro)), delta * np.arange(1.0, kmax + 1)


def pi0_geometric(beta, kmax):
    """Closed-form P[K=0] = 1/sum_{i=0}^{kmax} beta^{-i}, evaluated in log space
    (valid for every beta > 0, including beta = 1)."""
    if beta <= 0:
        return 0.0
    i = np.arange(kmax + 1)
    return float(np.exp(-logsumexp(-i * np.log(beta))))


def meanK_geometric(beta, kmax):
    """E[K] of the constant-rate pool, pi_k proportional to beta^{-k}."""
    if beta <= 0:
        return float(kmax)
    i = np.arange(kmax + 1)
    lw = -i * np.log(beta)
    w = np.exp(lw - logsumexp(lw))
    return float(w @ i)


def name_window_constant(beta, kmax, T, lam_intro=1.0):
    if beta <= 0:
        return 1.0 if np.ndim(T) == 0 else np.ones(np.shape(T))
    b, d = name_rates_constant(kmax, lam_intro, beta * lam_intro)
    return bd_window(b, d, T)


def name_window_perunit(delta, kmax, T, lam_intro=1.0):
    if delta <= 0:
        return 1.0 if np.ndim(T) == 0 else np.ones(np.shape(T))
    b, d = name_rates_perunit(kmax, lam_intro, delta)
    return bd_window(b, d, T)


def timeavg_availability(beta, kmax, n, lam_a, mu):
    """Closed-form time-average availability (Theorem closedform)."""
    return (1.0 - pi0_geometric(beta, kmax)) * addr_timeavg(n, lam_a, mu)


def interval_availability(beta, kmax, T, n, lam_a, mu, lam_intro=1.0):
    """Exact interval availability of the paper's canonical model."""
    return (name_window_constant(beta, kmax, T, lam_intro)
            * addr_window(n, lam_a, mu, T))


# =========================================================================== #
#  2. General CTMCs, linear in named rate parameters
# =========================================================================== #
class LinearCTMC:
    """A finite CTMC whose off-diagonal rates are linear in named parameters.

    transitions(state) returns an iterable of (next_state, component, weight):
    the transition fires at rate  weight * rates[component].  The reachable
    state space is generated once by breadth-first search from `initial`
    (only transitions with weight > 0 are followed), so it must not depend on
    the parameter values (true whenever all rate parameters are positive).
    up(state) -> bool marks the up states.
    """

    def __init__(self, initial, transitions, up, max_states=200000):
        states = [initial]
        index = {initial: 0}
        trip = {}                                  # comp -> (rows, cols, vals)
        queue = deque([initial])
        while queue:
            s = queue.popleft()
            i = index[s]
            for t, comp, w in transitions(s):
                if w <= 0 or t == s:
                    continue
                if t not in index:
                    index[t] = len(states)
                    states.append(t)
                    queue.append(t)
                    if len(states) > max_states:
                        raise RuntimeError("state space too large")
                r, c, v = trip.setdefault(comp, ([], [], []))
                r.append(i)
                c.append(index[t])
                v.append(float(w))
        N = len(states)
        self.states = states
        self.index = index
        self.N = N
        self.M = {comp: sp.csr_matrix((v, (r, c)), shape=(N, N))
                  for comp, (r, c, v) in trip.items()}
        self.up = np.array([bool(up(s)) for s in states])

    # -- assembly --------------------------------------------------------- #
    def Q(self, **rates):
        missing = set(self.M) - set(rates)
        if missing:
            raise ValueError(f"missing rate parameters: {sorted(missing)}")
        off = sp.csr_matrix((self.N, self.N))
        for comp, M in self.M.items():
            if rates[comp] != 0:
                off = off + rates[comp] * M
        out = np.asarray(off.sum(axis=1)).ravel()
        return (off - sp.diags(out)).tocsr()

    def stationary(self, **rates):
        return ctmc_stationary(self.Q(**rates))

    def timeavg(self, **rates):
        return float(self.stationary(**rates)[self.up].sum())

    def window(self, T, **rates):
        Q = self.Q(**rates)
        return ctmc_window(Q, self.up, T)

    def flux(self, comp, reward, **rates):
        """Stationary rate of transitions of component `comp`, each weighted by
        reward(state, next_state) (e.g. the number of units removed)."""
        Q = self.Q(**rates)
        pi = ctmc_stationary(Q)
        M = self.M[comp].tocoo()
        tot = 0.0
        for i, j, w in zip(M.row, M.col, M.data):
            tot += pi[i] * w * rates[comp] * reward(self.states[i], self.states[j])
        return tot


def ctmc_stationary(Q):
    """Stationary law of an irreducible CTMC with generator Q (dense or sparse).
    Solves pi Q = 0 with the last balance equation replaced by sum(pi) = 1."""
    N = Q.shape[0]
    if N == 1:
        return np.ones(1)
    if N <= _DENSE_MAX:
        A = (Q.toarray() if sp.issparse(Q) else np.asarray(Q)).T.copy()
        A[-1, :] = 1.0
        rhs = np.zeros(N)
        rhs[-1] = 1.0
        pi = np.linalg.solve(A, rhs)
    else:
        A = sp.csr_matrix(Q).T.tocsr()
        A = sp.vstack([A[:-1, :], sp.csr_matrix(np.ones((1, N)))]).tocsc()
        rhs = np.zeros(N)
        rhs[-1] = 1.0
        pi = spsolve(A, rhs)
    if pi.min() < -1e-9:
        raise RuntimeError(f"stationary solve produced negative mass {pi.min():.2e}")
    pi = np.clip(pi, 0.0, None)
    return pi / pi.sum()


def ctmc_window(Q, up_mask, T, pi=None):
    """pi_U expm(Q_UU T) 1 for a stationary CTMC (T scalar or array)."""
    if pi is None:
        pi = ctmc_stationary(Q)
    U = np.flatnonzero(up_mask)
    Ts = np.atleast_1d(np.asarray(T, dtype=float))
    scalar = np.ndim(T) == 0
    if len(U) == 0:
        out = np.zeros_like(Ts)
    else:
        if sp.issparse(Q):
            QUU = Q[U][:, U]
        else:
            QUU = sp.csr_matrix(np.asarray(Q)[np.ix_(U, U)])
        ones = np.ones(len(U))
        piU = pi[U]
        out = np.empty_like(Ts)
        for k, t in enumerate(Ts):
            if len(U) <= _DENSE_MAX:
                u = expm(QUU.toarray() * t) @ ones
            else:
                u = expm_multiply(QUU * t, ones)
            out[k] = piU @ u
    out = np.clip(out, 0.0, 1.0)
    return float(out[0]) if scalar else out


# =========================================================================== #
#  3. Model chains used by the exact experiments (exact_experiments.py)
# =========================================================================== #
def batch_name_chain(kmax, b):
    """Constant-rate pool with bursty burns: events at rate lam_disc/b remove
    min(b, K) units (rotation_game.simulate_domain with burn_batch=b), so the
    mean burn throughput is lam_disc whenever K >= b.
    Rates: intro (mint), disc (burn-event rate, already divided by b)."""
    def trans(K):
        out = []
        if K < kmax:
            out.append((K + 1, "intro", 1.0))
        if K >= 1:
            out.append((max(0, K - b), "disc", 1.0 / b))
        return out
    return LinearCTMC(kmax, trans, lambda K: K >= 1)


def strategic_chain(kmax, policy, j=None, r=0):
    """Strategic-timing censor with an optional defender reserve.

    State (A, R, D): A active (served, discoverable) live units, R reserve
    units (live but never served, hence undiscoverable), D discovered-but-not-
    yet-blocked active units, 0 <= D <= A, A + R <= kmax, R <= r.

    Defender.  Mints at rate lam_intro while A + R < kmax. A mint goes to the
    active pool if A == 0, else to the reserve if R < r, else to the active
    pool ("serve from K - r units").  Whenever the active pool becomes empty
    and R > 0, all reserve units activate at once (A <- R, R <- 0, D <- 0).

    Censor.  Discovers undiscovered active units at aggregate rate lam_disc
    (while A - D >= 1); new units arrive undiscovered. On each discovery
    D <- D + 1 and the blocking policy decides whether to strike:
      'poisson'      block each unit on discovery (equals the constant-rate
                     pool of the paper);
      'batch'        strike (block all D discovered units) when D == j; if the
                     pool can never reach j discovered units the censor waits
                     for more mints;
      'batch_or_all' strike when D == j or when D == A (all active discovered);
      'strike_all'   strike when D == A, i.e. the whole active pool is
                     discovered (blocking it empties the active pool).
    The system is up iff A >= 1.
    Rates: intro, disc.
    """
    if policy not in ("poisson", "batch", "batch_or_all", "strike_all"):
        raise ValueError(policy)
    if policy in ("batch", "batch_or_all") and (j is None or j < 1):
        raise ValueError("batch policies need j >= 1")

    def block(A, R, D, nb):
        A, D = A - nb, D - nb
        if A == 0 and R > 0:
            A, R, D = R, 0, 0
        return (A, R, D)

    def trans(s):
        A, R, D = s
        out = []
        if A + R < kmax:
            if A == 0:
                ns = (1, R, D)
            elif R < r:
                ns = (A, R + 1, D)
            else:
                ns = (A + 1, R, D)
            out.append((ns, "intro", 1.0))
        if A - D >= 1:
            D2 = D + 1
            if policy == "poisson":
                ns = block(A, R, D2, 1)
            elif policy == "batch":
                ns = block(A, R, D2, D2) if D2 == j else (A, R, D2)
            elif policy == "batch_or_all":
                ns = block(A, R, D2, D2) if (D2 == j or D2 == A) else (A, R, D2)
            else:  # strike_all
                ns = block(A, R, D2, D2) if D2 == A else (A, R, D2)
            out.append((ns, "disc", 1.0))
        return out

    return LinearCTMC((0, 0, 0), trans, lambda s: s[0] >= 1)


def censor_best_response_timeavg(kmax, lam_intro, lam_disc, tol=1e-13,
                                 max_iter=500000):
    """Best timing policy against the time-average metric (no reserve).

    Average-reward MDP on states (A, D), 0 <= D <= A <= kmax (A live units,
    D of them discovered but unblocked). Events: mint (rate lam_intro while
    A < kmax, arrives undiscovered) and discovery (rate lam_disc while
    A - D >= 1). After every event the censor, who observes (A, D), may block
    any number b <= D of the discovered units. Reward rate 1{A = 0}; the censor
    maximizes the long-run fraction of time the pool is empty. Solved by
    relative value iteration on the uniformized chain (rate lam_intro +
    lam_disc; self-loops make it aperiodic).

    Returns dict(g=optimal down fraction, policy=b[A,D] array (pre-decision
    state), iterations, span).
    """
    K = kmax
    Lam = lam_intro + lam_disc
    pi_, pd_ = lam_intro / Lam, lam_disc / Lam
    valid = np.tril(np.ones((K + 1, K + 1), dtype=bool))      # D <= A
    r = np.zeros((K + 1, K + 1))
    r[0, 0] = 1.0
    V = np.zeros((K + 1, K + 1))
    A_idx, D_idx = np.nonzero(valid)
    mintA = np.where(A_idx < K, A_idx + 1, A_idx)
    discD = np.where(A_idx - D_idx >= 1, D_idx + 1, D_idx)

    def best_post(V):
        """M[A,D] = max_{b<=D} V[A-b, D-b] and the maximizing b (ties -> fewer
        blocks)."""
        M = np.full_like(V, -np.inf)
        arg = np.zeros(V.shape, dtype=int)
        for A in range(K + 1):
            for D in range(A + 1):
                if D == 0:
                    M[A, D], arg[A, D] = V[A, D], 0
                else:
                    if V[A, D] >= M[A - 1, D - 1] - 1e-15:
                        M[A, D], arg[A, D] = V[A, D], 0
                    else:
                        M[A, D], arg[A, D] = M[A - 1, D - 1], arg[A - 1, D - 1] + 1
        return M, arg

    # diagonals c = A - D: blocking b units moves (A,D) -> (A-b, D-b) along
    # the same diagonal, so M is a running maximum along each diagonal
    diags = [(np.arange(c, K + 1), np.arange(0, K + 1 - c)) for c in range(K + 1)]

    def best_post_value(V):
        M = np.empty_like(V)
        for a_i, d_i in diags:
            M[a_i, d_i] = np.maximum.accumulate(V[a_i, d_i])
        return M

    it, span = 0, np.inf
    g = None
    while it < max_iter:
        it += 1
        M = best_post_value(V)
        TV = np.zeros_like(V)
        TV[A_idx, D_idx] = (r[A_idx, D_idx] + pi_ * M[mintA, D_idx]
                            + pd_ * M[A_idx, discD])
        diff = (TV - V)[valid]
        span = diff.max() - diff.min()
        g = 0.5 * (diff.max() + diff.min())
        V = TV - TV[0, 0]
        V[~valid] = 0.0
        if span < tol:
            break
    M, arg = best_post(V)
    pol = np.where(valid, arg, -1)
    return {"g": float(g), "policy": pol, "iterations": it, "span": float(span)}


def policy_chain(kmax, policy):
    """CTMC of the (A, D) pool under a deterministic blocking policy
    policy[A, D] = number of discovered units blocked right after an event
    leaves the pool in pre-decision state (A, D). Rates: intro, disc."""
    def post(A, D):
        b = int(policy[A, D])
        return (A - b, D - b)

    def trans(s):
        A, D = s
        out = []
        if A < kmax:
            out.append((post(A + 1, D), "intro", 1.0))
        if A - D >= 1:
            out.append((post(A, D + 1), "disc", 1.0))
        return out
    return LinearCTMC((0, 0), trans, lambda s: s[0] >= 1)


def providers_chain(P, kp, mode):
    """P providers with kp slots each; state = occupancy counts (n_0..n_kp),
    n_l = number of providers holding l live units (sum n_l = P).

    mode 'pooled' (the model the paper uses): mints at total rate lam_intro go
      to a uniformly chosen non-full provider; takedowns at total rate lam_disc
      hit a uniformly chosen NON-EMPTY provider and empty it (full-capacity
      censor).
    mode 'idle', the idle-clock model (E9), read as provider-initiated
      suspensions: every provider has its own mint clock lam_intro/P (while not
      full) and its own takedown clock lam_disc/P (while non-empty); a takedown
      empties it.
    The system is up iff some provider holds a live unit.
    Rates: intro, disc.
    """
    if mode not in ("pooled", "idle"):
        raise ValueError(mode)

    def trans(s):
        out = []
        nf = sum(s[:kp])
        ne = sum(s[1:])
        for lvl in range(kp):
            if s[lvl] > 0:
                w = s[lvl] / nf if mode == "pooled" else s[lvl] / P
                t = list(s)
                t[lvl] -= 1
                t[lvl + 1] += 1
                out.append((tuple(t), "intro", w))
        for lvl in range(1, kp + 1):
            if s[lvl] > 0:
                w = s[lvl] / ne if mode == "pooled" else s[lvl] / P
                t = list(s)
                t[lvl] -= 1
                t[0] += 1
                out.append((tuple(t), "disc", w))
        return out

    init = (P,) + (0,) * kp
    return LinearCTMC(init, trans, lambda s: s[0] < P)


def exposure_chain(kmax, rho):
    """Mint-time exposure: state (E, U), E exposed and U unexposed live units,
    E + U <= kmax. A mint (rate lam_intro while E+U < kmax) is exposed with
    probability rho; exposed units are burned pre-emptively at per-unit rate
    theta; usage burns (aggregate rate lam_disc while E+U >= 1) hit a uniformly
    random live unit. Up iff E + U >= 1. Rates: intro, disc, theta.
    (theta = infinity is the single pool with intro rate (1-rho) lam_intro;
    see exposure_window_inf.)"""
    def trans(s):
        E, U = s
        out = []
        if E + U < kmax:
            out.append(((E + 1, U), "intro", rho))
            out.append(((E, U + 1), "intro", 1.0 - rho))
        if E > 0:
            out.append(((E - 1, U), "theta", float(E)))
        L = E + U
        if L >= 1:
            out.append(((E - 1, U), "disc", E / L))
            out.append(((E, U - 1), "disc", U / L))
        return out
    return LinearCTMC((0, 0), trans, lambda s: s[0] + s[1] >= 1)


def addr_sweep_generator(n, lam_a, mu, s):
    """Address layer with synchronized discovery. Each endpoint is discovered at
    total rate lam_a: individually at rate (1-s) lam_a and through a sweep
    (one event that blocks every clear endpoint at once) at rate s*lam_a, so
    each endpoint's marginal is still the two-state chain (lam_a, mu).
    c -> c+1 at mu (n-c); c -> c-1 at (1-s) lam_a c; c -> 0 at s lam_a (c>=1).
    Returns a dense generator on {0..n}."""
    Q = np.zeros((n + 1, n + 1))
    for c in range(n + 1):
        if c < n:
            Q[c, c + 1] += mu * (n - c)
        if c >= 1:
            Q[c, c - 1] += (1.0 - s) * lam_a * c
            Q[c, 0] += s * lam_a
    np.fill_diagonal(Q, 0.0)
    np.fill_diagonal(Q, -Q.sum(axis=1))
    return Q


# =========================================================================== #
#  4. Range blocking of a provider's address space (crisis regime)
# =========================================================================== #
def p_range(g, lam_a, mu):
    """Per-endpoint blocked probability when a fraction g of the provider's
    address space is range-blocked and each rotation draws a fresh address
    uniformly from that space:  p(g) = g + (1-g) lam_a/(lam_a+mu)
                                     = (lam_a + mu g)/(lam_a + mu).
    Derivation: an endpoint leaves 'clear' at rate lam_a + mu g (discovery, or
    a rotation that lands in the blocked range) and leaves 'blocked' at rate
    mu (1-g) (a rotation that lands in clear space), so it is the two-state
    chain with rates (lam_a + mu g, mu (1-g))."""
    g = float(g)
    return (lam_a + mu * g) / (lam_a + mu)


def address_factor_providers(gs, ns, lam_a, mu):
    """Time-average address factor 1 - prod_i p(g_i)^{n_i} for endpoints split
    over providers with (independent) range-blocked fractions g_i.
    gs, ns: sequences (per provider). Endpoints are independent, so the joint
    all-blocked probability is the product of per-endpoint probabilities."""
    logp = 0.0
    for g, k in zip(gs, ns):
        p = p_range(g, lam_a, mu)
        if k > 0:
            if p <= 0:
                return 1.0
            logp += k * np.log(p)
    return float(1.0 - np.exp(logp))


def address_factor_regime(g_crisis, pi_c, n, P, lam_a, mu, mode="common",
                          g_normal=0.0):
    """Regime-averaged address factor with crisis fraction pi_c.

    n endpoints are split evenly over P providers (n must be divisible by P).
    mode 'common': all providers are in crisis together a fraction pi_c of the
      time (e.g. a national range-blocking order):
        (1-pi_c) A(g_normal) + pi_c A(g_crisis).
    mode 'independent': each provider is independently in crisis a fraction
      pi_c of the time (provider-specific blocking):
        sum_m Binom(m; P, pi_c) [1 - p(g_c)^{m n/P} p(g_n)^{(P-m) n/P}].
    Plug measured range-blocked fractions in as g_crisis / g_normal."""
    if n % P:
        raise ValueError("n must be divisible by P")
    k = n // P
    if mode == "common":
        a_n = address_factor_providers([g_normal] * P, [k] * P, lam_a, mu)
        a_c = address_factor_providers([g_crisis] * P, [k] * P, lam_a, mu)
        return (1.0 - pi_c) * a_n + pi_c * a_c
    if mode == "independent":
        from scipy.stats import binom
        tot = 0.0
        for m in range(P + 1):
            gs = [g_crisis] * m + [g_normal] * (P - m)
            tot += binom.pmf(m, P, pi_c) * address_factor_providers(
                gs, [k] * P, lam_a, mu)
        return float(tot)
    raise ValueError(mode)


def addr_window_range(g, n, lam_a, mu, T):
    """Address-layer window probability on one provider with range-blocked
    fraction g: the clear-count chain with discovery rate lam_a + mu g and
    recovery rate mu (1-g) per endpoint."""
    if g >= 1:
        return 0.0 if np.ndim(T) == 0 else np.zeros(np.shape(T))
    return addr_window(n, lam_a + mu * g, mu * (1.0 - g), T)


def addr_window_providers(gs, ns, lam_a, mu, T):
    """Address-layer window probability with endpoints split over providers
    with range-blocked fractions g_i (independent providers). Builds the joint
    clear-count chain (Kronecker sum of the per-provider chains); the only
    down state is 'every endpoint blocked'."""
    gens = []
    for g, k in zip(gs, ns):
        if k == 0:
            continue
        la, m = lam_a + mu * g, mu * (1.0 - g)
        Q = np.zeros((k + 1, k + 1))
        for c in range(k + 1):
            if c < k:
                Q[c, c + 1] = m * (k - c)
            if c > 0:
                Q[c, c - 1] = la * c
        np.fill_diagonal(Q, -Q.sum(axis=1))
        gens.append(sp.csr_matrix(Q))
    Qj = gens[0]
    for G in gens[1:]:
        Qj = sp.kronsum(G, Qj, format="csr")    # kronsum(A,B) = A(x)I + I(x)B
    N = Qj.shape[0]
    up = np.ones(N, dtype=bool)
    up[0] = False                               # all counts zero is index 0
    return ctmc_window(Qj.tocsr(), up, T)


# =========================================================================== #
#  5. Frontiers by root finding
# =========================================================================== #
def beta_star(avail, alpha, lo=1e-6, hi=2.0, hi_max=1e4, xtol=1e-10):
    """Largest beta with avail(beta) >= alpha, for avail decreasing in beta.

    Returns (beta_star, status): status 'ok', 'none' (avail(lo) < alpha: no
    beta > 0 suffices) or 'above' (avail(hi_max) >= alpha)."""
    if avail(lo) < alpha:
        return None, "none"
    while avail(hi) >= alpha:
        hi *= 2.0
        if hi > hi_max:
            return None, "above"
    root = brentq(lambda b: avail(b) - alpha, lo, hi, xtol=xtol, rtol=1e-13,
                  maxiter=500)
    return float(root), "ok"


def check_single_crossing(avail, alpha, root, lo=1e-3, npts=60):
    """Evaluate avail on a grid around the root and confirm one sign change.
    Returns True if avail - alpha is >= 0 left of the root and <= 0 right."""
    if root is None:
        return None
    grid = np.unique(np.concatenate([
        np.linspace(max(lo, 0.02 * root), root * 0.999, npts // 2),
        np.linspace(root * 1.001, 3.0 * root + 0.5, npts // 2)]))
    vals = np.array([avail(b) for b in grid]) - alpha
    left = vals[grid < root]
    right = vals[grid > root]
    return bool(np.all(left >= -1e-12) and np.all(right <= 1e-12))


def frontier_interval(alpha, T, n, lam_a, mu, kmax, lam_intro=1.0):
    """Convenience: exact interval frontier beta*(alpha, T) of the canonical
    model (constant-rate pool, independent address layer) for any rates.
    Rates are in any common unit; T in the same time unit. Returns
    (beta*, status) with status 'ok', 'none' or 'above' (see beta_star)."""
    aT = addr_window(n, lam_a, mu, T)
    if aT <= alpha:
        return None, "none"
    f = lambda b: name_window_constant(b, kmax, T, lam_intro) * aT
    return beta_star(f, alpha)


def frontier_timeavg(alpha, n, lam_a, mu, kmax):
    """Convenience alias for beta_star_avg with the argument order of
    frontier_interval (time-average frontier, closed form)."""
    return beta_star_avg(alpha, kmax, n, lam_a, mu)


def beta_star_avg(alpha, kmax, n, lam_a, mu):
    """Time-average frontier beta*_avg (Theorem frontier): the root of
    (1 - pi0(beta, kmax)) c_a = alpha (closed-form availability, numerically
    exact root). Returns (value, status)."""
    ca = addr_timeavg(n, lam_a, mu)
    if ca <= alpha:
        return None, "none"
    return beta_star(lambda b: (1.0 - pi0_geometric(b, kmax)) * ca, alpha)


# =========================================================================== #
#  6. Discovery-delay Laplace transform (general discovery, Lemma general)
# =========================================================================== #
def laplace_from_cdf(cdf, mu, breakpoints=()):
    """p = E[exp(-mu D)] = P(D < I), I ~ Exp(mu), computed as
    int_0^inf mu e^{-mu x} F(x) dx (bounded integrand, robust quadrature)."""
    f = lambda x: mu * np.exp(-mu * x) * cdf(x)
    pts = sorted(set([0.0] + [float(b) for b in breakpoints if b > 0]))
    total, err = 0.0, 0.0
    edges = pts + [np.inf]
    for a, b in zip(edges[:-1], edges[1:]):
        v, e = quad(f, a, b, limit=400, epsabs=1e-13, epsrel=1e-11)
        total += v
        err += e
    return total, err


# =========================================================================== #
#  self-test
# =========================================================================== #
def _selftest():
    rng = np.random.default_rng(1)
    worst = 0.0
    for _ in range(40):
        m = int(rng.integers(1, 25))
        b = rng.uniform(0.05, 5, m)
        d = rng.uniform(0.05, 5, m)
        T = float(rng.uniform(0.1, 20))
        worst = max(worst, abs(bd_window(b, d, T) - bd_window_dense(b, d, T)))
    print(f"spectral vs dense expm (40 random chains): max |diff| = {worst:.2e}")
    # LinearCTMC vs birth-death on the constant pool
    ch = batch_name_chain(8, 1)
    for beta in (0.3, 0.661, 1.0, 1.7):
        w1 = ch.window(5.0, intro=1.0, disc=beta)
        w2 = name_window_constant(beta, 8, 5.0)
        assert abs(w1 - w2) < 1e-11, (w1, w2)
        assert abs(ch.timeavg(intro=1.0, disc=beta)
                   - (1 - pi0_geometric(beta, 8))) < 1e-12
    print("LinearCTMC(batch b=1) == birth-death pool: ok")
    # address stationary vs closed form
    for n in (1, 3, 8):
        b, d = addr_rates(n, 1.0, 3.0)
        pi = bd_stationary(b, d)
        assert abs(pi[0] - 0.25 ** n) < 1e-15
    print("address stationary P[c=0] = p^n: ok")
    # Krylov branch vs spectral branch on the same chains
    global _SPECTRAL_MAX
    old = _SPECTRAL_MAX
    worst = 0.0
    for m, beta, T in ((300, 1.0, 5.0), (1200, 0.9, 20.0), (600, 1.3, 1.0)):
        b, d = name_rates_constant(m, 1.0, beta)
        _SPECTRAL_MAX = 10 ** 6
        v1 = bd_window(b, d, T)
        _SPECTRAL_MAX = 10
        v2 = bd_window(b, d, T)
        worst = max(worst, abs(v1 - v2))
    _SPECTRAL_MAX = old
    print(f"spectral vs Krylov (m = 300..1200): max |diff| = {worst:.2e}")
    # strategic poisson == constant pool
    ch = strategic_chain(8, "poisson", r=2)
    w1 = ch.window(5.0, intro=1.0, disc=0.7)
    assert abs(w1 - name_window_constant(0.7, 8, 5.0)) < 1e-10
    print("strategic('poisson', r=2) == constant pool: ok")
    # providers P=kmax pooled == single pool
    ch = providers_chain(8, 1, "pooled")
    w1 = ch.window(5.0, intro=1.0, disc=0.8)
    assert abs(w1 - name_window_constant(0.8, 8, 5.0)) < 1e-10
    print("providers(P=8,kp=1,pooled) == constant pool: ok")
    # exposure rho=0 == single pool
    ch = exposure_chain(8, 0.0)
    w1 = ch.window(5.0, intro=1.0, disc=0.8, theta=1.0)
    assert abs(w1 - name_window_constant(0.8, 8, 5.0)) < 1e-10
    print("exposure(rho=0) == constant pool: ok")
    # sweep chain stationary
    Q = addr_sweep_generator(8, 1.0, 3.0, 1.0)
    pi = ctmc_stationary(Q)
    assert abs(pi[0] - 1.0 / (1.0 + 24.0)) < 1e-14
    print("sweep chain P[c=0] = lam_a/(lam_a + n mu): ok")
    print("self-test passed")


if __name__ == "__main__":
    _selftest()
